#!/bin/bash

if ! command -v docker-machine > /dev/null 2>&1;
then
    echo "  - You do not appear to have docker-machine installed - perhaps it's not in your PATH?"
    exit 1
fi

if ! docker-machine active > /dev/null 2>&1;
then
    echo "  - There is no active docker-machine. Please run: eval \"\$(docker-machine env <machine-name>)\""
    exit 1
fi


if ! command -v watch > /dev/null 2>&1;
then
    echo "  - You do not appear to have watch installed - perhaps it's not in your PATH?"
    exit 1
fi

declare -r ACTIVE_MACHINE="$(docker-machine active)"
declare -r WORKING_DIRECTORY="$(pwd)"
declare EXCLUDE_FLAGS=""

ssh-add "$HOME/.docker/machine/machines/${ACTIVE_MACHINE}/id_rsa"

docker-machine ssh "$ACTIVE_MACHINE" tce-load -wi rsync
docker-machine ssh "$ACTIVE_MACHINE" "sudo mkdir -p $WORKING_DIRECTORY && sudo chown docker:docker -R $WORKING_DIRECTORY"

if [[ -f '.rsyncignore' ]];
then
	EXCLUDE_FLAGS="--exclude-from='.rsyncignore'"
fi

watch -n1 rsync "$EXCLUDE_FLAGS" -rlptDv ./ "docker@$(docker-machine ip "$ACTIVE_MACHINE"):$WORKING_DIRECTORY"
